# Generated by Django 6.0.3 on 2026-04-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtail_localize_dashboard", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnippetTranslationProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="The primary key of the source snippet"
                    ),
                ),
                (
                    "translated_object_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The primary key of the translated snippet",
                    ),
                ),
                (
                    "percent_translated",
                    models.IntegerField(
                        default=0, help_text="Percentage of segments translated (0-100)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The content type shared by source and translated snippet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "translated_locale",
                    models.ForeignKey(
                        help_text="The locale of the translated snippet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippet_translation_progress",
                        to="wagtailcore.locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snippet Translation Progress",
                "verbose_name_plural": "Snippet Translation Progress",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["percent_translated"], name="snip_prog_percent_idx"
                    ),
                    models.Index(fields=["last_updated"], name="snip_prog_updated_idx"),
                ],
                "unique_together": {
                    ("content_type", "source_object_id", "translated_object_id")
                },
            },
        ),
    ]
