# Generated by Django 6.1.1 on 2026-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_localize_dashboard", "0002_snippettranslationprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippettranslationprogress",
            name="percent_published",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Percentage of segments translated and pushed to a live target (0-100), or null if it has not been calculated yet",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="translationprogress",
            name="percent_published",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Percentage of segments translated and pushed to a live target (0-100), or null if it has not been calculated yet",
                null=True,
            ),
        ),
    ]
