# Generated by Django 5.0.14 on 2026-01-02 18:59

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Brief introduction to the article"
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Article author name", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Page",
                "verbose_name_plural": "Article Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="A short tagline for the homepage",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction text for the homepage"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1), ("image", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Image URL or path"},
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Product description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Product price (not translated)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Product SKU (not translated)",
                        max_length=50,
                    ),
                ),
                (
                    "features",
                    wagtail.fields.StreamField(
                        [("feature", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.TextBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Page",
                "verbose_name_plural": "Product Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
